# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for MovieDB
  # Clean Architecture
  pod 'MGArchitecture', '0.4.0'
  pod 'MGAPIService', '0.5.0'
  pod 'MGLoadMore', '0.3.0'
    
  # Core
  pod 'ObjectMapper', '3.3'
  pod 'Reusable', '4.0.4'
  pod 'Then', '2.4'
  pod 'MJRefresh', '3.1'
    
  # Rx
  pod 'NSObject+Rx', '4.4'
  pod 'RxDataSources', '3.1'
    
  # Core Data
  pod 'MagicalRecord', '2.3'
    
  # UI
  pod 'MBProgressHUD', '1.1'
  pod 'SDWebImage', '5.0'
  pod 'RAMAnimatedTabBarController'
  pod 'TTSegmentedControl'
  pod 'Cosmos', '~> 19.0'

  target 'MovieDBTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
